# Generated by Django 2.1.5 on 2019-02-09 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(max_length=300)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
