# Generated by Django 2.1.5 on 2019-02-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190209_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Person',
        ),
    ]
