# Generated by Django 2.1.5 on 2019-02-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190212_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='rice',
            new_name='rice_how_store',
        ),
    ]
