# Generated by Django 2.1.5 on 2019-02-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20190212_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.ManyToManyField(to='people.EducationType'),
        ),
    ]
