# Generated by Django 2.1.5 on 2019-02-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20190212_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AlterField(
            model_name='person',
            name='knows_lassa_can_prevent',
            field=models.BooleanField(default=False),
        ),
    ]
