# Generated by Django 2.1.5 on 2019-02-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20190212_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='risk',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='person',
            name='sick',
            field=models.FloatField(default=0.0),
        ),
    ]
