# Generated by Django 2.1.5 on 2019-02-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20190212_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cultivate_rice',
        ),
        migrations.RemoveField(
            model_name='person',
            name='knows_lassa',
        ),
        migrations.RemoveField(
            model_name='person',
            name='knows_lassa_can_kill',
        ),
        migrations.RemoveField(
            model_name='person',
            name='knows_lassa_can_prevent',
        ),
        migrations.RemoveField(
            model_name='person',
            name='knows_lassa_can_treat',
        ),
        migrations.RemoveField(
            model_name='person',
            name='knows_lassa_cause',
        ),
        migrations.RemoveField(
            model_name='person',
            name='knows_lassa_how_prevent',
        ),
        migrations.RemoveField(
            model_name='person',
            name='knows_lassa_know_signs',
        ),
        migrations.RemoveField(
            model_name='person',
            name='knows_lassa_what_treat',
        ),
        migrations.RemoveField(
            model_name='person',
            name='rice_how_store',
        ),
        migrations.AddField(
            model_name='person',
            name='can_kill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='can_prevent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='can_treat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='care',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='care_by_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='care_by_family_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='cause',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='contact',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='contact_7',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='distance_treatment',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='dry_garri',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='dump',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='dump1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='dump2',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='early_treatment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='eat_maize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='eat_rat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='family_fever_recovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='family_get_fever',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='family_get_fever_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='far_dump',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='farm_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='farm_type',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='farm_type_4',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='farm_type_other',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='farmer_type_4',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='farmer_type_other',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='fever_cause',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='fever_cause_4',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='fever_intensity',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='fever_treatment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='fever_treatment_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='fever_treatment_hospital',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='food_to_farm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='gov_hospital_name',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='gps_id',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='had_lassa_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='how_kill_rat',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='how_prevent',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='if_local_name',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='person',
            name='if_local_name_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='info_on_lassa',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='info_on_lassa_7',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='kill_rat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='kill_rat_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='know_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='know_contact_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='know_fever_cause',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='know_fever_cause_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='know_lf_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='know_lf_patient_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='knows_of_lassa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='knows_of_lassa1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='last_fever',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='local_name',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='make_garri_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='mastomys_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='mis_hospital_name',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.CharField(default='unknown', max_length=512),
        ),
        migrations.AddField(
            model_name='person',
            name='occupation_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='occupation_2',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='occupation_9',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='other_contact',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='other_fever_cause',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='other_info_on_lassa',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='other_occupation',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='other_relationship',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='other_signs',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='patient_name',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='priv_hospital_name',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='questions',
            field=models.CharField(default='unknown', max_length=512),
        ),
        migrations.AddField(
            model_name='person',
            name='rat_month',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='rat_often',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='rat_time',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='rat_time_4',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='rats_present_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='relationship',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='relationship_7',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='rice',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='see_dump',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='see_dump_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='seek_treatment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='seek_treatment_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='seek_treatment_2',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='signs',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='signs_5',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='store_food',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='store_garri',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='store_maize',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='tell_treatment_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='tell_treatment_type_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='temperature',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='person',
            name='treatment_type',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='what_treat',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='where_fever_treatment',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='where_fever_treatment_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='where_rat',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='where_rat_4',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='where_rat_other',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='where_seek_treatment',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='where_seek_treatment_1',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='where_seek_treatment_2',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='where_seek_treatment_3',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='who_live_with',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='who_sharefood_with',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='who_work_with',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='why_catch',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='why_catch2',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='why_no_treatment',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='year',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='community_name',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.RemoveField(
            model_name='person',
            name='education',
        ),
        migrations.AddField(
            model_name='person',
            name='education',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.RemoveField(
            model_name='person',
            name='farmer_type',
        ),
        migrations.AddField(
            model_name='person',
            name='farmer_type',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='fear_range',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(default='female', max_length=8),
        ),
        migrations.AlterField(
            model_name='person',
            name='lga_name',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.RemoveField(
            model_name='person',
            name='occupation',
        ),
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='state_name',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='town_name',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.RemoveField(
            model_name='person',
            name='trader_occupation',
        ),
        migrations.AddField(
            model_name='person',
            name='trader_occupation',
            field=models.CharField(default='unknown', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='village_name',
            field=models.CharField(default='unknown', max_length=64),
        ),
        migrations.DeleteModel(
            name='EducationType',
        ),
        migrations.DeleteModel(
            name='FarmerType',
        ),
        migrations.DeleteModel(
            name='LassaCause',
        ),
        migrations.DeleteModel(
            name='LassaPrevent',
        ),
        migrations.DeleteModel(
            name='LassaTreatment',
        ),
        migrations.DeleteModel(
            name='OccupationType',
        ),
        migrations.DeleteModel(
            name='RiceType',
        ),
        migrations.DeleteModel(
            name='TraderOccupationType',
        ),
    ]
