# Generated by Django 2.1.5 on 2019-02-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20190225_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='can_kill',
            field=models.CharField(default='False', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='can_treat',
            field=models.CharField(default='False', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='early_treatment',
            field=models.CharField(default='False', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='if_local_name',
            field=models.CharField(default='False', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='seek_treatment',
            field=models.CharField(default='False', max_length=128),
        ),
    ]
