# Generated by Django 2.1.5 on 2019-02-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20190226_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='income',
            field=models.FloatField(default=0.0),
        ),
    ]
