export const examplePeople = [{
  id:"7d516f50-02bf-40c3-8e83-5bc4321b8861",
  name:"Person Guy",
  rice_how_store:
    ["Dry and store in sack",
     "Sun dry"],
  occupation: ["Clergy man"],
  farmer_type: ["Cassava farmer"],
  trader_occupation: ["Rice trader"],
  education: ["Primary"],
  knows_lassa_cause: ["Does not know"],
  knows_lassa_what_treat: ["Prayers"],
  knows_lassa_how_prevent: ["Kill rats", "Hygiene", "No bush meat","Prayer"],
  created_at:"2019-02-12T21:12:44.172000Z",
  community_name:"Agbaja",
  village_name:"Onuenyim",
  town_name:"Izzi",
  state_name:"Ebonyi",
  lga_name:"Izzi",
  interview_date:"2018-02-13T00:00:00Z",
  store_gps_latitude:6.730219416869391,
  store_gps_longitude:8.23686964718199,
  age:36,
  gender:"Male",
  income:25000,
  family_size:4,
  knows_lassa:true,
  knows_lassa_know_signs:false,
  knows_lassa_can_kill:false,
  knows_lassa_can_treat:true,
  knows_lassa_can_prevent:true,
  take_vaccine:true,
  had_lassa:true,
  fear:true,
  fear_range:3,
  rats_present:true,
  mastomys:true,
  farm:true,
  cultivate_rice:true,
  eat_rice:false,
  make_garri:false,
  drink_garri:true,
  sick:0.0,
  risk:0.0
},
{
  id:"7d516f50-02bf-40c3-8e83-5bc4321b1231",
  name:"Random Person",
  rice_how_store:
    ["Dry and store in sack",
     "Sun dry"],
  occupation: ["Clergy man"],
  farmer_type: ["Cassava farmer"],
  trader_occupation: ["Rice trader"],
  education: ["Primary"],
  knows_lassa_cause: ["Does not know"],
  knows_lassa_what_treat: ["Prayers"],
  knows_lassa_how_prevent: ["Kill rats", "Hygiene", "No bush meat","Prayer"],
  created_at:"2019-02-12T21:12:44.172000Z",
  community_name:"Agbaja",
  village_name:"Onuenyim",
  town_name:"Izzi",
  state_name:"Ebonyi",
  lga_name:"Izzi",
  interview_date:"2018-02-13T00:00:00Z",
  store_gps_latitude:6.730219416869391,
  store_gps_longitude:8.23686964718199,
  age:45,
  gender:"Female",
  income:25000,
  family_size:4,
  knows_lassa:true,
  knows_lassa_know_signs:false,
  knows_lassa_can_kill:false,
  knows_lassa_can_treat:true,
  knows_lassa_can_prevent:true,
  take_vaccine:true,
  had_lassa:true,
  fear:true,
  fear_range:3,
  rats_present:true,
  mastomys:true,
  farm:true,
  cultivate_rice:true,
  eat_rice:false,
  make_garri:false,
  drink_garri:true,
  sick:0.0,
  risk:0.0
},
{
  id:"7d516f50-02bf-40c3-8e83-5bc4321b5631",
  name:"John Doe",
  rice_how_store:
    ["Dry and store in sack",
     "Sun dry"],
  occupation: ["Clergy man"],
  farmer_type: ["Cassava farmer"],
  trader_occupation: ["Rice trader"],
  education: ["Primary"],
  knows_lassa_cause: ["Does not know"],
  knows_lassa_what_treat: ["Prayers"],
  knows_lassa_how_prevent: ["Kill rats", "Hygiene", "No bush meat","Prayer"],
  created_at:"2019-02-12T21:12:44.172000Z",
  community_name:"Agbaja",
  village_name:"Onuenyim",
  town_name:"Izzi",
  state_name:"Ebonyi",
  lga_name:"Izzi",
  interview_date:"2018-02-13T00:00:00Z",
  store_gps_latitude:6.730219416869391,
  store_gps_longitude:8.23686964718199,
  age:12,
  gender:"Male",
  income:25000,
  family_size:4,
  knows_lassa:true,
  knows_lassa_know_signs:false,
  knows_lassa_can_kill:false,
  knows_lassa_can_treat:true,
  knows_lassa_can_prevent:true,
  take_vaccine:true,
  had_lassa:true,
  fear:true,
  fear_range:3,
  rats_present:true,
  mastomys:true,
  farm:true,
  cultivate_rice:true,
  eat_rice:false,
  make_garri:false,
  drink_garri:true,
  sick:0.0,
  risk:0.0
}];
